/* Generated by wayland-scanner 1.24.0 */

#ifndef BANNER_AHB_V1_CLIENT_PROTOCOL_H
#define BANNER_AHB_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_banner_ahb_v1 The banner_ahb_v1 protocol
 * @section page_ifaces_banner_ahb_v1 Interfaces
 * - @subpage page_iface_banner_ahb_v1 - Android gralloc buffers behind dma-buf wl_buffers
 * @section page_copyright_banner_ahb_v1 Copyright
 * <pre>
 *
 * Copyright 2026 The412Banner
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct banner_ahb_v1;
struct wl_buffer;

#ifndef BANNER_AHB_V1_INTERFACE
#define BANNER_AHB_V1_INTERFACE
/**
 * @page page_iface_banner_ahb_v1 banner_ahb_v1
 * @section page_iface_banner_ahb_v1_desc Description
 *
 * Zero-copy window layers on Android. A Vulkan swapchain image that the
 * client allocated as an Android AHardwareBuffer (gralloc) is still shared
 * as a dma-buf through zwp_linux_dmabuf_v1, so the compositor can import
 * and draw it the usual way. This interface additionally hands the
 * compositor the AHardwareBuffer itself, once per wl_buffer, so the
 * compositor can put the buffer straight on an Android SurfaceControl
 * layer (SurfaceFlinger / the display hardware composite it) without
 * copying it.
 *
 * The AHardwareBuffer travels over a Unix socket: the client creates a
 * socketpair, writes the buffer's handle into one end with
 * AHardwareBuffer_sendHandleToUnixSocket, then sends the other end in the
 * attach request. The compositor reads it with
 * AHardwareBuffer_recvHandleFromUnixSocket and closes the socket. Its
 * reference to the AHardwareBuffer lives as long as the wl_buffer (plus
 * whatever the display still holds).
 *
 * The compositor advertises this global whenever it can put buffers on a
 * display layer at all; whether it WANTS gralloc buffers right now is the
 * mode event (version 2), sent on bind and every time the user switches
 * zero-copy on or off during the session. A client decides per swapchain,
 * when it creates the swapchain, from the last mode it received, and a
 * client whose live swapchain was built for the other mode retires it
 * (VK_ERROR_OUT_OF_DATE_KHR on its next acquire or present) so the program
 * rebuilds it for the new mode. Buffers of the old swapchain stay fully
 * presentable until then: an attached AHardwareBuffer keeps its association
 * for the wl_buffer's lifetime whatever the mode is now. A version 1
 * client (no mode event) keeps deciding from its own environment. A
 * client that does not see the global (or does not want it) allocates
 * swapchain images the standard way; nothing else changes.
 *
 * Synchronisation stays implicit: the dma-buf carries the client's render
 * fence (DMA_BUF_IOCTL_IMPORT_SYNC_FILE by the client's driver), the
 * compositor exports it as the layer's acquire fence, and the compositor
 * imports the display's release fence into the dma-buf before it sends
 * wl_buffer.release, so the client's next acquire waits on it.
 * @section page_iface_banner_ahb_v1_api API
 * See @ref iface_banner_ahb_v1.
 */
/**
 * @defgroup iface_banner_ahb_v1 The banner_ahb_v1 interface
 *
 * Zero-copy window layers on Android. A Vulkan swapchain image that the
 * client allocated as an Android AHardwareBuffer (gralloc) is still shared
 * as a dma-buf through zwp_linux_dmabuf_v1, so the compositor can import
 * and draw it the usual way. This interface additionally hands the
 * compositor the AHardwareBuffer itself, once per wl_buffer, so the
 * compositor can put the buffer straight on an Android SurfaceControl
 * layer (SurfaceFlinger / the display hardware composite it) without
 * copying it.
 *
 * The AHardwareBuffer travels over a Unix socket: the client creates a
 * socketpair, writes the buffer's handle into one end with
 * AHardwareBuffer_sendHandleToUnixSocket, then sends the other end in the
 * attach request. The compositor reads it with
 * AHardwareBuffer_recvHandleFromUnixSocket and closes the socket. Its
 * reference to the AHardwareBuffer lives as long as the wl_buffer (plus
 * whatever the display still holds).
 *
 * The compositor advertises this global whenever it can put buffers on a
 * display layer at all; whether it WANTS gralloc buffers right now is the
 * mode event (version 2), sent on bind and every time the user switches
 * zero-copy on or off during the session. A client decides per swapchain,
 * when it creates the swapchain, from the last mode it received, and a
 * client whose live swapchain was built for the other mode retires it
 * (VK_ERROR_OUT_OF_DATE_KHR on its next acquire or present) so the program
 * rebuilds it for the new mode. Buffers of the old swapchain stay fully
 * presentable until then: an attached AHardwareBuffer keeps its association
 * for the wl_buffer's lifetime whatever the mode is now. A version 1
 * client (no mode event) keeps deciding from its own environment. A
 * client that does not see the global (or does not want it) allocates
 * swapchain images the standard way; nothing else changes.
 *
 * Synchronisation stays implicit: the dma-buf carries the client's render
 * fence (DMA_BUF_IOCTL_IMPORT_SYNC_FILE by the client's driver), the
 * compositor exports it as the layer's acquire fence, and the compositor
 * imports the display's release fence into the dma-buf before it sends
 * wl_buffer.release, so the client's next acquire waits on it.
 */
extern const struct wl_interface banner_ahb_v1_interface;
#endif

/**
 * @ingroup iface_banner_ahb_v1
 * @struct banner_ahb_v1_listener
 */
struct banner_ahb_v1_listener {
	/**
	 * whether the compositor wants gralloc swapchain images now
	 *
	 * Sent once right after bind and again whenever the compositor's
	 * zero-copy state flips (the in-game switch). enabled = 1:
	 * swapchains created from now on should use gralloc
	 * AHardwareBuffers and attach them; 0: standard buffers. A live
	 * swapchain built for the other value should be retired by the
	 * client (out of date) so the program rebuilds it; until it is,
	 * its buffers are shown as before.
	 * @param enabled 1 = gralloc swapchain images wanted, 0 = not
	 * @since 2
	 */
	void (*mode)(void *data,
		     struct banner_ahb_v1 *banner_ahb_v1,
		     uint32_t enabled);
};

/**
 * @ingroup iface_banner_ahb_v1
 */
static inline int
banner_ahb_v1_add_listener(struct banner_ahb_v1 *banner_ahb_v1,
			   const struct banner_ahb_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) banner_ahb_v1,
				     (void (**)(void)) listener, data);
}

#define BANNER_AHB_V1_DESTROY 0
#define BANNER_AHB_V1_ATTACH 1

/**
 * @ingroup iface_banner_ahb_v1
 */
#define BANNER_AHB_V1_MODE_SINCE_VERSION 2

/**
 * @ingroup iface_banner_ahb_v1
 */
#define BANNER_AHB_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_banner_ahb_v1
 */
#define BANNER_AHB_V1_ATTACH_SINCE_VERSION 1

/** @ingroup iface_banner_ahb_v1 */
static inline void
banner_ahb_v1_set_user_data(struct banner_ahb_v1 *banner_ahb_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) banner_ahb_v1, user_data);
}

/** @ingroup iface_banner_ahb_v1 */
static inline void *
banner_ahb_v1_get_user_data(struct banner_ahb_v1 *banner_ahb_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) banner_ahb_v1);
}

static inline uint32_t
banner_ahb_v1_get_version(struct banner_ahb_v1 *banner_ahb_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) banner_ahb_v1);
}

/**
 * @ingroup iface_banner_ahb_v1
 *
 * Buffers already attached keep their AHardwareBuffer association.
 */
static inline void
banner_ahb_v1_destroy(struct banner_ahb_v1 *banner_ahb_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) banner_ahb_v1,
			 BANNER_AHB_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) banner_ahb_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_banner_ahb_v1
 *
 * Associates the AHardwareBuffer readable from socket with the
 * (already created) dma-buf wl_buffer. width, height and stride
 * (pixels) describe the gralloc allocation; modifier_hi/lo is the DRM
 * format modifier the dma-buf was shared with (the same value passed to
 * zwp_linux_buffer_params_v1.add); image_count is the number of images
 * in the swapchain this buffer belongs to (for the compositor's log).
 * Sent once per wl_buffer, before the buffer is first attached to a
 * surface.
 */
static inline void
banner_ahb_v1_attach(struct banner_ahb_v1 *banner_ahb_v1, struct wl_buffer *buffer, int32_t socket, uint32_t width, uint32_t height, uint32_t stride, uint32_t modifier_hi, uint32_t modifier_lo, uint32_t image_count)
{
	wl_proxy_marshal_flags((struct wl_proxy *) banner_ahb_v1,
			 BANNER_AHB_V1_ATTACH, NULL, wl_proxy_get_version((struct wl_proxy *) banner_ahb_v1), 0, buffer, socket, width, height, stride, modifier_hi, modifier_lo, image_count);
}

#ifdef  __cplusplus
}
#endif

#endif
